FROM jenkins/jenkins:lts
USER root
RUN apt-get update && \
	apt-get install -y docker.io && \
	apt-get install -y docker-compose && \
	usermod -aG docker jenkins && \
	service docker start

EXPOSE 8085 3000 9090

USER jenkins
