# prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] # Prometheus scraping itself

  - job_name: 'addressbook'
    metrics_path: /metrics      # Path your app exposes metrics on
    static_configs:
      # This will be resolved via 'extra_hosts' in docker-compose.yml
      - targets: ['host.docker.internal:8085']
